# Generated by Django 4.2.7 on 2023-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usu',
            new_name='acesso',
        ),
    ]
